import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "AirMax 1",
    brand: "Nike",
    description: "AirMax 1 - Latest model",
    price: 5000,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5615d24c-d429-4f6f-9457-daa083e99dcc/air-max-genome-shoes-nxMDJ2.png",
  },
  {
    _id: uuid(),
    title: "AirMax 1",
    brand: "Nike",
    description: "AirMax 1 - Latest model",
    price: 5000,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5615d24c-d429-4f6f-9457-daa083e99dcc/air-max-genome-shoes-nxMDJ2.png",
  },
  {
    _id: uuid(),
    title: "AirMax 2",
    brand: "Nike",
    description: "AirMax 2 - Latest model",
    price: 6999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5615d24c-d429-4f6f-9457-daa083e99dcc/air-max-genome-shoes-nxMDJ2.png",
  },
  {
    _id: uuid(),
    title: "AirMax 3",
    brand: "Nike",
    description: "AirMax 3 - Latest model",
    price: 7999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5615d24c-d429-4f6f-9457-daa083e99dcc/air-max-genome-shoes-nxMDJ2.png",
  },
  {
    _id: uuid(),
    title: "AirMax 4",
    brand: "Nike",
    description: "AirMax 4 - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5615d24c-d429-4f6f-9457-daa083e99dcc/air-max-genome-shoes-nxMDJ2.png",
  },
  {
    _id: uuid(),
    title: "Puma 1",
    brand: "Puma",
    description: "Puma - Latest model",
    price: 7999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Puma 2",
    brand: "Puma",
    description: "Puma - Latest model",
    price: 2456,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Puma 3",
    brand: "Puma",
    description: "Puma - Latest model",
    price: 6543,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Puma 4",
    brand: "Puma",
    description: "Puma - Latest model",
    price: 7767,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Puma 5",
    brand: "Puma",
    description: "Puma - Latest model",
    price: 10555,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Adidas 1",
    brand: "Adidas",
    description: "Adidas - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Adidas 2",
    brand: "Adidas",
    description: "Adidas - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Adidas 3",
    brand: "Adidas",
    description: "Adidas - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Adidas 4",
    brand: "Adidas",
    description: "Adidas - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Adidas 5",
    brand: "Adidas",
    description: "Adidas - Latest model",
    price: 2999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Asics 4",
    brand: "Asics",
    description: "Asics - Latest model",
    price: 1999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Asics 1",
    brand: "Asics",
    description: "Asics - Latest model",
    price: 1999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Asics 2",
    brand: "Asics",
    description: "Asics - Latest model",
    price: 1999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "Asics 3",
    brand: "Asics",
    description: "Asics - Latest model",
    price: 1999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: true,
    productImage: "https://picsum.photos/208",
  },
  {
    _id: uuid(),
    title: "AirMax 80",
    brand: "Nike",
    description: "AirMax 80 - Latest model",
    price: 9999,
    category: "sneaker",
    originalPrice: 9999,
    inStock: false,
    productImage: "https://picsum.photos/208",
  },
];
